export { payAndFetch, settleX402 } from "./payment.js";
export {
  fetchGate,
  fetchGateByDomain,
  verifyPayment,
  getPaymentHistory,
  SessionExpiredError,
  getMeAgent,
  getAgentSummary,
  getAgentCaps,
  putAgentCaps,
  resetAgentDayCap,
  getAgentScope,
  putAgentScope,
  setAgentPause,
  listAgentKeys,
  createAgentKey,
  rotateAgentKey,
  revokeAgentKey,
  listAgentReceipts,
  deviceStart,
  devicePoll,
  meSessionRequest,
  getLinkSchema,
  validateLink,
  createLink,
  listLinks,
  getLinkDetail,
  revokeLink,
  listMerchantPayments,
  listSubscribers,
  getMerchantProfile,
  putMerchantProfile,
  verifyMerchantDomain,
  initiateLinkPayment,
  claimLinkPayment,
} from "./api.js";
export {
  signPayLink,
  computeTemplateHash,
  canonicalJson,
  stringifyNumbers,
} from "./pay-link-signer.js";
export type { PayLinkLit, SignedPayLink } from "./pay-link-signer.js";
export {
  loadConfig,
  generateWallet,
  getWalletAddress,
  ensureConfigDir,
  saveSession,
} from "./config.js";
export type { LoadConfigResult } from "./config.js";
export {
  USDC_BASE,
  MOCK_USDC_SEPOLIA,
  DEFAULT_CONFIG,
  SESSION_COOKIE_NAME,
} from "./types.js";
export type {
  PaymentRequirements,
  FacilitatorOption,
  GateResponse,
  VerifiedPaymentResponse,
  PaymentResult,
  XenarchConfig,
  MeAgentProfile,
  AgentSummary,
  AgentCaps,
  AgentCapsPut,
  CapResetResult,
  ScopeMode,
  ScopeRuleItem,
  ScopeReadResult,
  ScopeRuleInput,
  PauseResult,
  AgentApiKeySummary,
  AgentApiKeyIssued,
  AgentReceiptItem,
  AgentReceiptList,
  DeviceStartResponse,
  DevicePollResponse,
  PayLinkSchemaResponse,
  PayLinkSchemaField,
  PayLinkFieldIssue,
  PayLinkValidateResponse,
  LitValue,
  PayLinkCreateBody,
  PayLinkCreateResponse,
  PayLinkListItem,
  PayLinkListResponse,
  PayLinkDetail,
  PayLinkRevokeResponse,
  MerchantPaymentItem,
  MerchantPaymentListResponse,
  SubscriberListItem,
  SubscriberListResponse,
  MerchantProfileBody,
  MerchantProfileResponse,
  PayLinkInitiateResponse,
  PayLinkClaimResponse,
} from "./types.js";
export type { PaymentHistoryItem, FetchGateResult } from "./api.js";
